version: '3'
services:
  db:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    depends_on:
       - db
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/communiteer
    ports:
      - "3000:3000"
    restart: always
    links:
      - db
