version: '3'
services:
  db:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d

  web:
    build: .
    tty: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/communiteer
    ports:
      - "3000:3000"
    restart: always
    links:
      - db
    depends_on:
      - db
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - communiteer_link

networks:
  communiteer_link:
    external: true
