version: '3'
services:
  db:
    image: mysql:8.0.25
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: communiteer_development
    ports:
      - "3306:3306"

  web:
    build: .
    depends_on:
      - db
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && rails db:migrate"
    volumes:
      - .:/communiteer
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true