
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: rootpass
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default
  database: communiteer_development
  

test:
  <<: *default
  database: communiteer_test

production:
  <<: *default
  database: communiteer
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host:     <%= Rails.application.credentials.db[:host] %>
  port:     3306
  socket: /var/lib/mysql/mysql.sock
